name: Android Release
on:
  push:
    tags:
      - "android@*"
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read
      actions: read
      security-events: write
  release:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "17"

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install depends
        run: sh install.sh

      - name: Read secrets
        env:
          SUPABASE_PROJECT_URL: ${{ secrets.SUPABASE_PROJECT_URL }}
          SUPABASE_PROJECT_KEY: ${{ secrets.SUPABASE_PROJECT_KEY }}
        run: |
          echo '' > .env
          echo 'SUPABASE_PROJECT_URL="${{ secrets.SUPABASE_PROJECT_URL }}"' >> .env
          echo 'SUPABASE_PROJECT_KEY="${{ secrets.SUPABASE_PROJECT_KEY }}"' >> .env
          echo '${{ secrets.GOOGLE_SERVICES }}' > src-capacitor/android/google-services.json

      - name: Build Quasar
        run: bun build:android:ci

      - name: Build zip update OTA
        run: bun build:capgo

      - name: Build Android App
        uses: anime-vsub/android-build-action@1.2.1
        with:
          project-path: src-capacitor/android
          output-path: apk-release.apk
          gradle-task: assembleRelease
          # build-type: bundle
          # package-name: git.shin.animevsub
          # keystore-content:  ${{ secrets.KEYSTORE_CONTENT }}
          # keystore-password: ${{ secrets.KEYSTORE_PASSWORD }}
          # keystore-alias:  ${{ secrets.KEYSTORE_ALIAS }}
          # browserstack-upload: true
          # browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
          # browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        if: ${{ failure() }}
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: tachibana-shin
          wait-timeout-minutes: 5

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: /home/runner/work/raiku-app/raiku-app
          signingKeyBase64: ${{ secrets.KEYSTORE_CONTENT }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "30.0.2"

      # Example use of `signedReleaseFile` output -- not needed
      - uses: actions/upload-artifact@v2
        with:
          name: apk-release.apk
          path: |
            {{steps.sign_app.outputs.signedReleaseFile}}
            src-capacitor/git.shin.raiku_*.zip

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: "android@"
          output-file: "false"
          git-branch: "main"
          skip-tag: "true"
          skip-git-pull: "true"

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: ${{steps.sign_app.outputs.signedReleaseFile}}
          body: ${{ steps.changelog.outputs.clean_changelog  }}
